gluster/centosci

heketi-functional.yml
This is a rewrite the XML specification to JJB format.
It has been tested by generating the XML and importing it in the CentOS CI. Running tests and aborting seems to work well.
=> Add heketi-functional job

nightly-rpm-builds.yml, scripts/nightly-builds/nightly-builds.sh
While adding these, drop the unmaintained versions 3.10 and 4.0.
It seems that 4.0 was not build for CentOS-6 yet, added the suitable
parameters to build the RPMs with mock.
=> Add nightly RPM builds for Gluster 4.1

scripts/common/get-node.sh
We have seen occasions where the heketi-functional job failed before any
test got executed. This results in failures like:
[gluster_heketi-functional] $ /bin/sh -xe /tmp/jenkins5285185003978476870.sh
+ ./bootstrap.sh heketi-centos-ci-tests.sh ghprbPullId=1281
++ basename heketi-centos-ci-tests.sh
+ EXEC_BIN=heketi-centos-ci-tests.sh
++ cat /home/gluster/workspace/gluster_heketi-functional/hosts
cat: /home/gluster/workspace/gluster_heketi-functional/hosts: No such file or directory
+ scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no heketi-centos-ci-tests.sh root@:heketi-centos-ci-tests.sh
ssh: Could not resolve hostname : Name or service not known
Because the 'hosts' file is missing, the hostname of the scp target is
empty.
This change adds a few simple checks for the 'cico' …
=> get-node: add error checking for failing cico

scripts/gluster-block/get-glusto-logs.sh, scripts/gluster-block/get-logs.yml, scripts/gluster-block/gluster_block_glusto_tests_config.yml.j2, scripts/gluster-block/jenkins-job-block.yml, scripts/gluster-block/run_glusto_main.sh, scripts/gluster-block/run_glusto_on_host.sh, scripts/gluster-block/setup-gluster-block-glusto.yml
This patch series adds the files needed to run glusto based tests(not per patch) on centos CI.
For now, I am assuming that the gluster-block related glusto libs are there in the glusto-tests repo and the test cases are in gluster-block repo. Therefore, the tests are run accordingly.
The same files can be modified for regression testing(triggered from Github PR) and glusto per patch testing. I will be sending a PR for that too.
[Fixes: bz#1598326](https://bugzilla.redhat.com/show_bug.cgi?id=1598326)
Signed-off-by: Bhumika Goyal <bgoyal@redhat.com>
=> gluster-block: add centos CI files for glusto tests 

scripts/nightly-builds/nightly-builds.sh
@kshlm reported an issue where nightly builds fail with the following error:
```
am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
if test -d "glusterfs-3.12.13"; then find "glusterfs-3.12.13" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "glusterfs-3.12.13" || { sleep 5 && rm -rf "glusterfs-3.12.13"; }; else :; fi
./nightly-builds.sh: line 72: syntax error near unexpected token `)'
Build step 'Execute shell' marked build as failure
```
It seems the `case` statement did not have the appropriate `;;`.
=> Fix syntax error in GlusterFS nightly-builds.sh script

heketi-functional.yml
This is a short term fix to deal with the fact that heketi functional tests are regularly timing out now, mainly due to the increased number of functional tests we've added. A longer term project to make the functional tests faster is needed but for now we're just going to increase the timeout.
=> heketi-functional: increase timeout to 3 hours

jobs/anteater-gcs.yml, jobs/scripts/anteater/gcs_infra.sh
Script to deploy the [GCS](https://github.com/gluster/gcs) infrastructure against which the [anteater](https://github.com/gluster/anteater) tests would be executed. The current script uses the vagrant based deployment from the GCS repo.
=> GCS infrastructure setup script for anteater

jobs/scripts/gluster-block/gluster-block-basic.sh
Currently, rsync is failing with:
```
rsync: mkdir "/gluster-block-nightly/7/x86_64" (in gluster) failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(587) [Receiver=3.0.9]
rsync: connection unexpectedly closed (178 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```
=> gluster-block: fix the repodir structure

jobs/glusterd2.yml
This is the only way we can make sure most devs can retrigger tests, I think
=> Add everyone in the org to the admin list

jobs/scripts/nightly-builds/nightly-builds.sh
With the update to CentOS 7.1810 it seems that yum changed behaviour a
little. For some (unclear at the moment) reason yum decides to install
centos-release-gluster-legacy instead of centos-release-gluster5.
By installing centos-release-storage-common *before* requesting to
install centos-release-gluster, yum picks the right version.
This is a workaround as installing centos-release-gluster on a cleanly
installed system should get the latest maintained Gluster release.
=> nightly-builds: install latest centos-release-gluster package

jobs/csi-driver-smoke.yml
The badge on the gluster-csi-driver project reflects the last run of the
smoke test. These tests are run against pull-requests, and not the
actual merged changes in master.
Introduce a 2nd job that runs the same smoke tests, but only once there
are pushed changes in the master branch. This uses the Jenkins GitHub
plugin as explained on the CentOS Wiki. As the page explains, it is
required to configure the GitHub project with a Webhook pointing to the
CentOS CI as well.
Once this change has been merged, the image in the README can be updated
to https://ci.centos.org/view/Gluster/job/gluster_csi-driver-master
URL: https://wiki.centos.org/QaWiki/CI/GithubIntegration
Updates: gluster/gluster-csi-driver#96
=> csi-driver: run smoke test on the master branch after merging changes

jobs/scripts/gluster-block/gluster-block-basic.sh
Fix the below error which is stopping the script.
error: Failed dependencies:
libtcmu = 1.4.0.83.g9d8a7e9-0.el7 is needed by tcmu-runner-1.4.0.83.g9d8a7e9-0.el7.x86_64
libtcmu.so.2()(64bit) is needed by tcmu-runner-1.4.0.83.g9d8a7e9-0.el7.x86_64
=> block: install libtcmu too, along with tcmu-runner

jobs/scripts/gluster-block/gluster-block-basic.sh
Using the gluster-block.repo file fails to fetch the repository metadata
and errors out like this:
http://artifacts.ci.centos.org/gluster/gluster-block-nightly/master/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
It seems the repodata is not generated at the right location. With this
change the repodata will be located alongside the RPMs, just as what is
configured in the .repo file.
Closes: #52
Signed-off-by: Niels de Vos <ndevos@redhat.com>
=> gluster-block/nightly: place repo metadata with the RPMs

jobs/build-rpms.yml, jobs/nightly-rpm-builds.yml, jobs/scripts/nightly-builds/nightly-builds.sh
GlusterFS 5 has been branched. Add it to the tests for nightly builds.
=> Add GlusterFS release-5 & release-6 branch to tests

jobs/scripts/nightly-builds/nightly-builds.sh
When passing `--depth 1` to `git clone`, only the last commit of the
master branch will be fetched. Changing branches afterwards does not
work, as no other branches have been downloaded.
In order to do nightly builds for non-master branches, the `--branch`
argument to `git clone` is required. With this, it is not needed anymore
to checkout the branch afterwards.
Fixes: b552df317a1 ("git clone with just depth 1 for glusterfs")
=> nightly-builds: fix shallow cloning of git repository for non-master branches

jobs/scripts/nightly-builds/nightly-builds.sh
When a git repository is shallow cloned, there are no tags available.
This makes ./build-aux/pkg-version spit out errors instead of a useable
version. Builds will fail with errors like
fatal: No names found, cannot describe anything.
By creating a VERSION file in the root of the git repository, the
./build-aux/pkg-version will not give any errors and building the
packages should work again.
Updates: #57 #59
=> nightly-builds: create a VERSION file to not need tags in the git repo

jobs/scripts/gluster-block/gluster-block-basic.sh
On RHEL and CentOS the libtirpc version is 0.2.4, but it still has
some bugs and could not work well, so just disable it.
More detail please see: gluster/gluster-block#221
=> gluster-blockd: configure without tirpc on CentOS

jobs/scripts/nightly-builds/nightly-builds.sh
The ./build-aux/pkg-version script in the glusterfs repository expects
that the VERSION starts with a 'v'. Without it, teh script is unable to
detect anything useful.
=> nightly-builds: VERSION should start with a 'v'

jobs/scripts/nightly-builds/nightly-builds.sh
There is no need to have a new version every day (night). By using the
date of the last commit in the package version, the packages will be
built, but the version/release stays the same. This reduces the number
of packages in the repository, and makes it more obvious what changes
were included. The git-hash is still part of the version as well.
=> nightly-builds: use date of last commit as part of the package version

jobs/scripts/gluster-block/lcov.sh
Similar to #60, but fixes in the proper script for lcov.
=> gluster-block/lcov: pass enable-tirpc=no for centos

jobs/scripts/gluster-block/clang-scan.sh, jobs/scripts/gluster-block/gluster-block-basic.sh, jobs/scripts/gluster-block/lcov.sh, jobs/scripts/gluster-block/setup-gluster-block-glusto.yml
tcmu-runner project uses tcmalloc now.
This memory allocater is part of gperftools, hence we need to install it.
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
=> gluster-block: add gperftools-devel as dependency

jobs/scripts/glusto/setup-glusto.yml
CentosCI is failing to setup glusto as it it unable
to upgrade pip as shown below:
https://ci.centos.org/job/gluster_glusto-patch-check/1472/consoleFull
Adding task to upgrade pip manually:
- name: Upgrading pip
command: "pip install --upgrade pip"
=> Adding task to upgrade pip in setup-glusto.yml file.

jobs/scripts/glusto/setup-glusto.yml
At present we only use a script called file_dir_ops.py in
glusto-tests to run IO. But the issue with file_dir_ops.py
is that it isn't that effective to create files. A better
tool which is often used is Crefi which can be used to create
a varity of fops.
Link to tool is avaliable here:
https://github.com/vijaykumar-koppad/Crefi
Hence to support running crefi in glustolibs I am adding a task
to setup crefi to setup-glusto.yml.
=> Adding task to setup-glusto.yml playbook to install crefi.

jobs/scripts/glusto/setup-glusto.yml
At present due to the changes in ansible lookup plugin seems to me failing for centos-ci for glusto-test. Modifying the path format in
task "Add entries to authorized_keys" to fix the issue. And also reformatting the task as per the new task structure used in ansible.
From:
```
- name: Add entries to authorized_keys
authorized_key: user=root key="{{ lookup('file', '/home/gluster/.ssh/glusto.pub')}}"
```
To:
```
- name: Add entries to authorized_keys
authorized_key:
user: root
state: present
key: "{{ lookup('file', '~/.ssh/glusto.pub') }}"
```
=> Fixing lookup plugin issues in setup-glusto.yml

jobs/scripts/glusto/setup-glusto.yml
setup-glusto.yml is still failing as shown below:
`
FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: ~/.ssh/glusto.pub"}
`
So reverting back to `/home/gluster/.ssh/glusto.pub` instead.
=> Reverting back to absolute path for glusto.pub

jobs/scripts/glusto/setup-glusto.yml
We have optimized the script file_dir_ops.py which is executed on clients to generated I/O
to generate more I/O in less time through patch [1]. This enahancement need numpy to be installed on all the clients. Hence I am adding a task to setup-glusto.yml playbook to install numpy on all clients.
Code added:
```
- name: Installing crefi using pip
pip:
name: crefi
state: present
```
[1] https://review.gluster.org/#/c/glusto-tests/+/23143/
=> Adding task to install numpy.

jobs/scripts/glusto/setup-glusto.yml
To run rsync based workloads on mounted volumes we
have added rsyncs functionality in file_dir_ops.py through
patch [1]. This requires sh module present on clients. Hence
a task has to be added to install sh module using pip in
setup-glusto.yml playbook.
[1] https://review.gluster.org/#/c/glusto-tests/+/18518/
=> Add task for installing sh on clients

jobs/scripts/glusto/templates/gluster_tests_config.yml.j2
Problem:
We don't have static ip support for the servers which are utilized
in CentOS-CI which doesn't allow us to setup ctdb server due to this
the testcases which have cifs mount_type in runs_on() fail with
the below error:
```
2020-01-02 07:39:21,719 INFO (run) root@172.19.3.97 (cp): smbclient -L localhost -U | grep -i -Fw gluster-testvol_replicated
2020-01-02 07:39:21,719 DEBUG (_get_ssh_connection) Retrieved connection from cache: root@172.19.3.97
2020-01-02 07:39:21,932 INFO (_log_results) RETCODE (root@172.19.3.97): 1
2020-01-02 07:39:21,932 ERROR (share_volume_over_smb) volume 'testvol_replicated' not accessible via SMB/CIFS share
2020-01-02 07:39:21,932 ERROR (setup_volume) Failed to export volume testvol_replicated as SMB Share
```
Solution:
Skip cifs mount type while running …
=> Edit gluster_tests_config.yml.j2 to run fuse and nfs mounts only.

jobs/scripts/glusto/setup-glusto.yml
xmlrunner  is no longer supported with python2, so when we try to run CentOS-CI 
on patches it fails with the below given stack trace:
```
18:29:51 Traceback (most recent call last):
18:29:51   File "/usr/bin/glusto", line 9, in <module>
18:29:51     load_entry_point('glusto==0.62', 'console_scripts', 'glusto')()
18:29:51   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
18:29:51     return get_distribution(dist).load_entry_point(group, name)
18:29:51   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
18:29:51     return ep.load()
18:29:51   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
18:29:51     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
18:29:51 …
```
=> Changing setup-glusto.yml playbook to install glusto with python3 

jobs/samba-integration.yml
This is adding integration of centos-ci with https://github.com/gluster/samba-integration/
=> Add job to run samba-integration tests

jobs/samba-integration.yml
To be able to rebase the PR to the target branch.
=> samba-integration: pass the ghprbTargetBranch variable to the job

jobs/scripts/common/bootstrap.sh
If more than one variable is passed, then the bootstrap.sh errors with
something like
`/bootstrap.sh: line 7: [: ghprbPullId=8: binary operator expected`
Making this safer.
=> bootstrap.sh: small fix

jobs/build-rpms.yml, jobs/nightly-rpm-builds.yml
This only adds the option to build for CentOS-8, but does not add the automated trigger in the nightly-rpm-builds job. We'll need to run some manual tests first to see if things function as they should.
GlusterFS 4.1 is end-of-life, so it has been removed as an option too.
Reported-by: Michael Adam (@obnoxxx)
=> build-rpms: update Jenkins job for testing builds on CentOS 8

jobs/samba-integration.yml
=> samba-integration: only run on PRs to branches master and centos-ci

jobs/scripts/nightly-builds/nightly-builds.sh
The variable RET was not set anyway.
And because of `set -e`, we exit on error, so useless to do error
tracking with a RET variable at this point.
=> nightly-builds: remove useless exit at the end

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
=> nightly-samba-builds: don't upload artifacts if running on a PR

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
The variable RET was not set anyway.
And because of `set -e`, we exit on error, so useless to do error
tracking with a RET variable at this point.
=> samba-nightly-builds: remove useless exit at the end

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
Testing the samba-nightly-build rpm by installing them in a vm before declaring success.
=> Samba nightly: test rpms install

jobs/samba-integration.yml
This is relying on https://github.com/gluster/samba-integration/pull/74
=> samba-integration: enable PR checking of the tests branch

jobs/scripts/glusto/setup-glusto.yml
To run git clone on the gluster volumes, need
git to be installed on the clients.
=> Install git on clients

jobs/scripts/glusto/setup-glusto.yml
Problem:
Currently, glusterfs installation on centos-ci is failing with dependency
libgfapi0.
Ref: https://ci.centos.org/job/gluster_glusto-patch-check/2217/console
Fix: 
Installing libgfapi0 prior to installation of glusterfs packages resolves the
issues. I tried it only local machine and it works fine.
Used the fix based on the comment
https://github.com/gluster/glusterfs/issues/1297#issuecomment-642626533
=> Install libgfapi0 prior to installation of gluster

jobs/scripts/glusto/setup-glusto.yml
Currently, gluster repo is created separately for 
server and client even though both the repos 
are the same.
As per the previous commit, libgfapi0 is not getting 
installed as gluster repo is not present under "Server
and Client tasks." so removing from the server and 
client sections and adding to  "Server and Client tasks."
=> Removing the redundancy of setting gluster repo 

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
Due to the shallow clone, rebasing the PR fails, like here:
https://ci.centos.org/job/gluster_nightly-samba-rpm-builds/108/console
Fix this by unshallowing the clone before doing the rebase.
=> nightly-samba-build: Fix rebasing PR on target branch.

jobs/scripts/glusto/setup-glusto.yml
Problem:
Patches like [1] which run Linux kernel untar fail on CentOS-CI as wget isn't present by default on the machines with the below error:
```
2020-10-21 09:34:56,781 INFO (run) root@172.19.2.49 (cp): wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.54.tar.xz
2020-10-21 09:34:56,781 DEBUG (_get_ssh_connection) Retrieved connection from cache: root@172.19.2.49
2020-10-21 09:34:56,833 INFO (_log_results) RETCODE (root@172.19.2.49): 127
2020-10-21 09:34:56,834 INFO (_log_results) STDERR (root@172.19.2.49)...
bash: wget: command not found
```
Solution:
Add task to install wget to setup-glusto.yml
Links:
[1] https://review.gluster.org/#/c/glusto-tests/+/25128/
=> Add step to install wget to glusto/setup-glusto.yml

jobs/scripts/glusto/setup-glusto.yml
wget was accidentally added to the pip list instead of yum list. Fixing it and sending a patch.
=> Move wget from pip to yum loop

jobs/samba-integration.yml
Fixes: https://github.com/gluster/samba-integration/issues/77
=> samba-integration: establish email notification

jobs/scripts/glusto/setup-glusto.yml
Problem:
glusterd start command fails due to issue[1], causing the centos-ci jobs to fail.
Fix:
Adding glusterfs-geo-replication to Install gluster task.
Issues:
[1] https://github.com/gluster/glusterfs/issues/1924
=> Add glusterfs-geo-replication to Install gluster task

jobs/scripts/glusto/setup-glusto.yml
Problem:
With the pytest version 6.2.1 doClassCleanups() are failing in glusto with the below error:
```
TypeError: _is_error_or_failure_exists() missing 1 required positional argument: 'self'
```
Fix:
Install pytest version 6.1.2 and py version 1.9.0 which can be removed one the issue is fixed in pytest
=> Add tasks to install pytest version 6.1.2 and py version 1.9.0

jobs/heketi-functional.yml
Fix build timeout err "Build timed out (after 180 minutes)."
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>
=> heketi: Increase heketi CI timeout to 5 hrs

jobs/glusto-patch-check.yml
We are currently moving glusto-tests from Gerrit(review.gluster.org) to Github workflow for which making changes to glusto-patch-check.yml.
Reference issue:  https://github.com/gluster/glusto-tests/issues/35
=> Update glusto-patch-check.yml for GitHub workflow

jobs/nightly-samba-rpm-builds.yml
With the use of job templates, we now have multiple checks to show in PRs.
=> samba-builds: update status-context of jobs to reflect multiple jobs

jobs/nightly-rpm-builds.yml
release-7 branch is EOL. 
https://docs.gluster.org/en/latest/release-notes/7.9/
Hence removing the daily builds on release-7.
=> release-7 branch is EOL

jobs/scripts/nightly-builds/nightly-builds.sh
Centos CI latest builds on rel-9 and devel fails due to this dependency
https://ci.centos.org/view/Gluster/job/gluster_build-rpms/15498/consoleText
=> added --disable-linux-io_uring flag for config

jobs/scripts/nightly-builds/nightly-builds.sh
We don't need some of the RPMs we install here.
=> Remove deps that are not needed

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
From BASH_BUILTIN(1) man page for `read`:
> The exit status is zero, unless end-of-file is encountered, read times out (in which case the status is greater than 128), a variable assignment error (such as assigning to a readonly variable) occurs, or an invalid file descriptor is supplied as the argument to -u.
So a return value of 1 doesn't mean that execution failed rather encountered EOF. Since successful exit status is a must for us to proceed with script execution, we switch to `readarray` bash builtin instead of `read` to return 0.
Closes #158
=> Use `readarray` instead of `read`

jobs/heketi-functional.yml
With introduction of '--release' option to `cico` command we are bound
to define 'CENTOS_VERSION' variable. See [1] for related change.
[1] 3cbdc28
Thanks to Anoop C S for the fix.
Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>
=> Define CENTOS_VERSION with a default

jobs/nightly-samba-rpm-builds.yml, jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
* Modify configuration to include jobs for building fedora RPMs.
* Introduce an intermediate parent directory to differentiate CentOS and
Fedora RPMs on CI artifacts.
=> Enable building fedora based RPMs

jobs/nightly-samba-rpm-builds.yml
With v4.15 getting [released](https://wiki.samba.org/index.php/Samba_Release_Planning), v4.13.x series is now **_Security fixes_** only mode and thus we are not interested in having nightly builds from such a very slow-moving target.
Related: https://github.com/gluster/samba-integration/pull/200
=> Enable Samba 4.15 test branch builds
