gd2-nightly-rpms.yml, scripts/gd2-nightly/build.sh
Depends on gluster/glusterd2#775
=> Add gd2-nightly-rpms job

glusterd2.yml, scripts/common/jenkins-job.py, scripts/common/run-test.sh
Signed-off-by: Deepshikha Khandelwal <dkhandel@redhat.com>
=> Add common scripts for centosci jobs

jobs/glusterd2.yml
Madhu Rajanna (@Madhu-1) can now trigger tests from first time PR
senders by using magic phrase 'add to whitelist'.
Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>
=> glusterd2: Add Madhu-1 as admin to PR job

jobs/glusterd2.yml
- Set property 'github:display-name'
- Add Madhu-1 to admins
=> Update job glusterd2

jobs/gluster-prometheus-nightly-rpms.yml, jobs/scripts/gluster-prometheus-nightly/build.sh
Signed-off-by: Aravinda VK <avishwan@redhat.com>
=> Nightly rpm job for gluster-prometheus project

jobs/gluster-block-basic.yml, jobs/scripts/gluster-block/gluster-block-basic.sh
=> gluster-block-basic: add a test to just build the gluster-block repo

jobs/scripts/gluster-block/gluster-block-basic.sh
Noticed that dependency was missing in previous version.
=> block: add more packages for the dependency

jobs/scripts/gluster-block/gluster-block-basic.sh
* set -e
* few more package dependency added
* copy the proper RPM paths.
=> block: more bug fixes

jobs/scripts/glusto/run-glusto.sh
Signed-off-by: Deepshikha khandelwal <dkhandel@redhat.com>
=> [GLUSTO-JOB]Remove functional test test_vvt.py from glusto

jobs/scripts/nightly-builds/nightly-builds.sh
So that checkout process is faster.
=> git clone with just depth 1 for glusterfs

jobs/gluster-block-lcov.yml, jobs/scripts/gluster-block/lcov.sh
Signed-off-by: Deepshikha khandelwal <dkhandel@redhat.com>
=> Add jenkins job to run lcov on gluster-block nightly

jobs/gluster-block-clang-scan.yml, jobs/scripts/gluster-block/clang-scan.sh
Signed-off-by: Deepshikha khandelwal <dkhandel@redhat.com>
=> Add centosci job for running clang-scan on gluster block

jobs/gluster-block-coverity.yml, jobs/scripts/common/get-node-to-ansible.sh, jobs/scripts/gluster-block/coverity.sh
- This PR contains the coverity analysis job for gluster-block using latest cov-build tool from scan.coverity.com
- Also there is a bug fix for clang scan job
=> Add a gluster-block coverity job

jobs/glusterfs-regression.yml, jobs/scripts/glusterfs/regression.sh
Signed-off-by: Amar Tumballi <amarts@gmail.com>
=>  added github based regression tests for glusterfs

jobs/glusterfs-regression.yml
Signed-off-by: Amar Tumballi <amarts@gmail.com>
=> glusterfs-regression: change bootstrap.sh path

jobs/nightly-samba-rpm-builds.yml, jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
This is for integration testing in the samba-integration project.
=> Create a job for doing nightly Samba RPM builds with gluster module.

jobs/nightly-samba-rpm-builds.yml, jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
=> nightly-samba-builds: trigger ci job on PR to the samba-build branch

jobs/heketi-functional.yml
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>
=> Add pkalever to admin-list in heketi-functional job

jobs/heketi-functional.yml
Signed-off-by: Raghavendra Talur <rtalur@redhat.com>
=> Add iamniting to admin-list in heketi-functional job

jobs/nightly-samba-rpm-builds.yml
=> nightly-samba-builds: establish email notification

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
=> nightly-samba-builds: log commands in script

jobs/scripts/glusto/setup-glusto.yml
We need to install sos for patch [1]. Hence adding step to install sos.
[1] https://review.gluster.org/#/c/glusto-tests/+/24770/
=> Add sos to glusto/setup-glusto.yml

jobs/build-rpms.yml, jobs/nightly-rpm-builds.yml, jobs/scripts/nightly-builds/nightly-builds.sh
=> corrects the branch name to pull the code from

jobs/scripts/nightly-builds/nightly-builds.sh
=> Fixed nightly build for centos-8

jobs/build-rpms.yml
=> Addes choice for release-8 branch to the job

jobs/build-rpms.yml
=> Fixed centosci branch name

jobs/scripts/nightly-builds/nightly-builds.sh
=> Fixed centos8 ci failure for glusterfs build

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
=> samba-build: fix system prep by using latest vagrant version

jobs/glusto-weekly-run.yml, jobs/scripts/glusto/run-glusto-main-all.sh
New job to run all glusto tests, triggers each Friday.
Temporary in this commit (for testing purpose) :
- running all dht tests
- duplicate "run-glusto-main.sh" and changed it for not interfering other jobs
Signed-off-by: Tamar Shacked <tshacked@redhat.com>
=> New job to run all glusto tests, triggers once a week (1st draft)

jobs/scripts/glusto/setup-glusto.yml
=> Change code to install pip version lower than 21.0

jobs/nightly-samba-rpm-builds.yml
=> nightly-samba-builds: adapt yaml after branch rename

jobs/gluster-block-basic.yml, jobs/gluster-block.yml
=> gluster-block: fix jobs after branch rename master->main

jobs/gluster-prometheus-nightly-rpms.yml
=> prometheus-nightly: fix job after rename master->main

jobs/build-rpms.yml
=> gluster rpm builds: fix job after branch rename master->main

jobs/glusto-weekly-run.yml
=> glusto-weekly: fix job after branch rename master->main

jobs/scripts/nightly-builds/nightly-builds.sh
rpcgen and liburing failed because of typo in --enablerepo "powertools"
=> rpcgen and liburing failed - enablerepo

jobs/nightly-samba-rpm-builds.yml
Closes https://github.com/gluster/samba-integration/issues/140
=> Trigger build on merge to samba-build branch

jobs/nightly-samba-rpm-builds.yml, jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
Depends on https://github.com/gluster/samba-integration/pull/163
Closes https://github.com/gluster/samba-integration/issues/134
=> Add jobs to build from Samba release branches

jobs/scripts/nightly-builds/nightly-builds.sh
Hi @msaju 
Please do review this PR.
Thank you
=> Fix issue with enablerepo for liburing

jobs/scripts/nightly-builds/nightly-builds.sh
Hi @msaju 
Please review this PR.
=> include update statement

jobs/scripts/nightly-builds/nightly-builds.sh
added rsync for centos 8 dependency
=> added rsync for centos 8 dependency

jobs/samba-integration.yml, jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
See commit messages for more details.
Closes #164
=> Fix failures due to requirement of new `--release` mandatory argument  

jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
Closes https://github.com/gluster/samba-integration/issues/173
=> Fix failures while bringing up vagrant machines on CentOS 8

jobs/scripts/nightly-builds/nightly-builds.sh
Hi @msaju,
Please review this PR.
Thanks,
=> Dependency resolution for tcmalloc library

jobs/build-rpms.yml, jobs/nightly-rpm-builds.yml, jobs/scripts/nightly-builds/nightly-builds.sh, tests/Containerfile
Signed-off-by: Rakshitha Kamath <rkamath@redhat.com>
=> Changes to support 8-stream

.github/workflows/deploy.yaml, jobs/ansible-infra.yml, jobs/build-rpms.yml, jobs/gluster-block-basic.yml, jobs/gluster-block.yml, jobs/gluster-prometheus-nightly-rpms.yml, jobs/glusto-patch-check.yml, jobs/glusto-weekly-run.yml, jobs/heketi-functional.yml, jobs/nightly-rpm-builds.yml, jobs/scripts/common/rsync.sh, tests/deploy-centos-ci.sh, tests/jenkins.conf
Signed-off-by: Rakshitha Kamath <rkamath@redhat.com>
=> Change the jenkins URL to the new ocp4 newspace

.github/workflows/deploy.yaml, jobs/ansible-infra.yml, jobs/build-rpms.yml, jobs/gluster-block-basic.yml, jobs/gluster-block.yml, jobs/gluster-prometheus-nightly-rpms.yml, jobs/glusto-patch-check.yml, jobs/glusto-weekly-run.yml, jobs/heketi-functional.yml, jobs/nightly-rpm-builds.yml, jobs/scripts/common/rsync.sh, tests/deploy-centos-ci.sh, tests/jenkins.conf
=> Revert "Change the jenkins URL to the new ocp4 newspace"
